version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    target-branch: main
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    target-branch: main
